# please change the name so it matches your project name
name: web-react-skeleton
services:
  vite:
    image: node:24.13-slim
    env_file:
      - .env
    entrypoint: /srv/app/entrypoint.sh
    ports:
      - "${VITE_PORT:-8000}:${VITE_PORT:-8000}"
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
